### PR TITLE
Add: add new option to hide/display post navigation in home/blog

### LINKED ISSUE #528: Customizer Preview: Some options do not work
Just found that the contextual post metas + contextual and general post navigation hide/show options do not work as expected.

For the general post navigation option the reason is simple.
The code misses the element retrieval:
https://github.com/presscustomizr/customizr/blob/master/inc/admin/js/theme-customizer-preview.js#L444
where do we define that var? Nowhere .. 
+
https://github.com/presscustomizr/customizr/blob/master/inc/admin/js/theme-customizer-preview.js#L464

the options prefix isn't needed anymore.

so easy fix

About the other issues:
This line is not right -> https://github.com/presscustomizr/customizr/blob/master/inc/admin/js/theme-customizer-preview.js#L418

Issues probably introduced during the big preview revamp.

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
also fix issue with some contextualized options not working in the
customizer preview (post metas, post/page navigation)
fixes #528

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
I have to say that the small system I created to recognize the context made this add very simple.
I'm satisfied :P

**Comment by Nikeo** [comment]
This is not what I had in mind, I should have defined it better sorry.

It has to be an option available for the blog on home only. not for the blog on another page.
Therefore the is_home() check is not enough.

in the customizer, this option should be located in content > front page and revealed when the user decides to display the blog posts on home.

the name of the option should also reflect this : 'tc_show_post_navigation_home'

**Comment by eri-trabiccolo** [comment]
Ah don't worry.
Basically this is what I had in mind 'cause I proposed it after the random posts PR, your specification came after.
So I haven't been clear ;)

It's basically the same PR.
It should still depend on the post navigation global option right?
And the blog, when not in front, will still be controlled.
So last question.. this -> https://github.com/presscustomizr/customizr/pull/527 
should be valid only for the blog on home either, right?
'Cause the original code provided by menakas impacted on the blog on another page too.
I think I have to change that too..

**Comment by eri-trabiccolo** [comment]
Ok, done.
Check if you like it when you can.
Let me know about https://github.com/presscustomizr/customizr/pull/527 too
even if the change to apply it only in home displaying the blog is very simple

**Pull request merged**
