### PR TITLE
Fix: category-picker front do not query for non existent categories

### PR DESCRIPTION
**Pull request by eri-trabiccolo**

### CODE REVIEW

**Comment by Nikeo** [comment]
Can you also add an option update on term deletion ?

**Comment by eri-trabiccolo** [comment]
:)
I thought you wanted that.
Do you think is useful having both?
I mean, the "honerous" part is the front one, so I think that if we decide for the reaction on deletion we can avoid the front one.
Anyway I'll add the "option update" to this PR, then we'll decide whether or not having both is useful. :D

**Comment by Nikeo** [comment]
yes I prefer to have both :)

**Comment by eri-trabiccolo** [comment]
Done,
I "wrote" two ways to update the option, you can chose the one you prefer.
If you don't like any of them I will cry :P

**Comment by Nikeo** [comment]
ah ah looks perfect Rocco. Put a smile on your face :)

**Comment by eri-trabiccolo** [comment]
Thanks $GOD :D

**Pull request merged**
