### PR TITLE
Fix: better handling of the simple-load event triggered on holders

### LINKED ISSUE #377: jquery: Simple load function doesn't work for the holders
fp holders cannot be simple-loaded because they do not have a source (?).

Looking for the reason..

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
fixes #377

### CODE REVIEW

**Comment by Nikeo** [comment]
Ok thanks for this fix. Let's implement it for now. We'll see if we can improve this in the future.

**Comment by eri-trabiccolo** [comment]
Probably the better thing will be fire the simple-load event inside the holder.js, if we want to do such a thing.

**Comment by Nikeo** [comment]
humm, this would implied to maintain a modified version of holder, which I'm not really keen to do...

**Comment by eri-trabiccolo** [comment]
Yes, that's why I went for this ugly hack :D

**Comment by Nikeo** [comment]
not that ugly Rocco ;)

**Comment by eri-trabiccolo** [comment]
:)

**Pull request merged**
