### PR TITLE
Category picker dev

### PR DESCRIPTION
**Pull request by Nikeo**
test

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
mmm what do you mean? :D 
what's happening ? :D

**Comment by Nikeo** [comment]
is the cat filtering supposed to work ?

**Comment by eri-trabiccolo** [comment]
well yes, worked here :D 
Let me check I may have changed something before the push

**Comment by Nikeo** [comment]
don't worry, I can't wait for the final PR tomorrow.

Looks good :)

**Comment by eri-trabiccolo** [comment]
The filtering works fine here.
Doesn't it there?
So I'll keep it as is, conditioning the control appearing to the options "posts on front" and or "page of posts" selected, then  will spend some time on polylang integration (have to make some tests), then I'll make the final Pull Request soon then.

**Comment by Nikeo** [comment]
did not test again.
Will test the final one.

ok.

Thanks

**Comment by eri-trabiccolo** [comment]
Ok, so with "looks good" you meant that you liked the code cleanup I guess: P

**Pull request closed without merging**
