### PR TITLE
Idea: add parallax classes and js only when slider exists

### PR DESCRIPTION
**Pull request by eri-trabiccolo**

### CODE REVIEW

**Comment by giorgioriccardi** [comment]
Nice! probably a similar approach would boost performance and happiness in the future of Ctz
Angular2 has something similar as a killer feature, take a look from [slide #9](http://www.slideshare.net/nirkaufman/angularjs-lazy-loading-techniques)

**Comment by Nikeo** [comment]
events events...
cool

**Comment by eri-trabiccolo** [comment]
@giorgioriccardi 
will look at it, interesting, thanks! :D

**Comment by Nikeo** [comment]
fn prefixes are not up to date anymore...

**Comment by eri-trabiccolo** [comment]
I redo it

**Comment by eri-trabiccolo** [comment]
Updated!

**Pull request merged**
